// ============================================================================
// STARTER NOTE — Station 2.
//
// Data access for users, following the same pattern as requests.store.js:
// parameterized queries, rows in/rows out, optional `db` for transactions.
//
// Target SQL contracts:
//   findByEmail(email)          SELECT ... WHERE email = $1      -> row | null
//   findById(id)                SELECT ... WHERE id = $1         -> row | null
//   insertUser({ email, passwordHash })
//       INSERT INTO users (email, password_hash) VALUES ($1, $2)
//       RETURNING ...                                            -> row
//
// Decisions already made for you by migration 003:
//   * id, role and created_at are generated by the database;
//   * role is NOT a parameter of insertUser — registration cannot choose it.
// ============================================================================
import { pool } from '../../database/pool.js';

export async function findByEmail(email, db = pool) {
  // TODO (station 2)
  throw new Error('TODO: findByEmail is not implemented yet.');
}

export async function findById(id, db = pool) {
  // TODO (station 2)
  throw new Error('TODO: findById is not implemented yet.');
}

export async function insertUser({ email, passwordHash }, db = pool) {
  // TODO (station 2)
  throw new Error('TODO: insertUser is not implemented yet.');
}
